standalone | Starting Airflow Standalone
standalone | Checking database is initialized
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [airflow.models.crypto] empty cryptography key - values will not be stored encrypted.
/home/adqdevops2/airflow-env/lib/python3.8/site-packages/flask_limiter/extension.py:333 UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
standalone | Database ready
triggerer  | ____________       _____________
triggerer  | ____    |__( )_________  __/__  /________      __
triggerer  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
triggerer  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
triggerer  | _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
triggerer  | [2025-04-16 06:27:52 +0000] [12814] [INFO] Starting gunicorn 23.0.0
triggerer  | [2025-04-16 06:27:52 +0000] [12814] [ERROR] Connection in use: ('::', 8794)
triggerer  | [2025-04-16 06:27:52 +0000] [12814] [ERROR] connection to ('::', 8794) failed: [Errno 98] Address already in use
scheduler  | ____________       _____________
scheduler  | ____    |__( )_________  __/__  /________      __
scheduler  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
scheduler  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
scheduler  | _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
scheduler  | [2025-04-16T06:27:53.000+0000] {executor_loader.py:258} INFO - Loaded executor: SequentialExecutor
scheduler  | [2025-04-16 06:27:53 +0000] [12819] [INFO] Starting gunicorn 23.0.0
scheduler  | [2025-04-16T06:27:53.057+0000] {scheduler_job_runner.py:950} INFO - Starting the scheduler
scheduler  | [2025-04-16 06:27:53 +0000] [12819] [ERROR] Connection in use: ('::', 8793)
scheduler  | [2025-04-16 06:27:53 +0000] [12819] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
scheduler  | [2025-04-16T06:27:53.067+0000] {scheduler_job_runner.py:957} INFO - Processing each file at most -1 times
scheduler  | [2025-04-16T06:27:53.074+0000] {manager.py:174} INFO - Launched DagFileProcessorManager with pid: 12820
scheduler  | [2025-04-16T06:27:53.084+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
scheduler  | [2025-04-16T06:27:53.085+0000] {settings.py:63} INFO - Configured default timezone UTC
scheduler  | [2025-04-16T06:27:53.100+0000] {scheduler_job_runner.py:1972} INFO - Marked 1 SchedulerJob instances as failed
scheduler  | [2025-04-16T06:27:53.148+0000] {manager.py:406} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2) when using sqlite. So we set parallelism to 1.
triggerer  | [2025-04-16T06:27:53.185+0000] {triggerer_job_runner.py:181} INFO - Setting up TriggererHandlerWrapper with handler <FileTaskHandler (NOTSET)>
triggerer  | [2025-04-16T06:27:53.187+0000] {triggerer_job_runner.py:237} INFO - Setting up logging queue listener with handlers [<RedirectStdHandler <stdout> (NOTSET)>, <TriggererHandlerWrapper (NOTSET)>]
triggerer  | [2025-04-16T06:27:53.212+0000] {triggerer_job_runner.py:338} INFO - Starting the triggerer
triggerer  | [2025-04-16 06:27:53 +0000] [12814] [ERROR] Connection in use: ('::', 8794)
triggerer  | [2025-04-16 06:27:53 +0000] [12814] [ERROR] connection to ('::', 8794) failed: [Errno 98] Address already in use
scheduler  | [2025-04-16 06:27:54 +0000] [12819] [ERROR] Connection in use: ('::', 8793)
scheduler  | [2025-04-16 06:27:54 +0000] [12819] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
webserver  | /home/adqdevops2/airflow-env/lib/python3.8/site-packages/flask_limiter/extension.py:333 UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
triggerer  | [2025-04-16 06:27:54 +0000] [12814] [ERROR] Connection in use: ('::', 8794)
triggerer  | [2025-04-16 06:27:54 +0000] [12814] [ERROR] connection to ('::', 8794) failed: [Errno 98] Address already in use
scheduler  | [2025-04-16 06:27:55 +0000] [12819] [ERROR] Connection in use: ('::', 8793)
scheduler  | [2025-04-16 06:27:55 +0000] [12819] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
triggerer  | [2025-04-16 06:27:55 +0000] [12814] [ERROR] Connection in use: ('::', 8794)
triggerer  | [2025-04-16 06:27:55 +0000] [12814] [ERROR] connection to ('::', 8794) failed: [Errno 98] Address already in use
webserver  | [2025-04-16 06:27:55 +0000] [12812] [INFO] Starting gunicorn 23.0.0
webserver  | Error: Already running on PID 8535 (or pid file '/home/adqdevops2/airflow/airflow-webserver.pid' is stale)
scheduler  | [2025-04-16 06:27:56 +0000] [12819] [ERROR] Connection in use: ('::', 8793)
scheduler  | [2025-04-16 06:27:56 +0000] [12819] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
standalone | Airflow is ready
standalone | Login with username: admin  password: k7sVk3qKSrP3PWHx
standalone | Airflow Standalone is for development purposes only. Do not use this in production!
triggerer  | [2025-04-16 06:27:56 +0000] [12814] [ERROR] Connection in use: ('::', 8794)
triggerer  | [2025-04-16 06:27:56 +0000] [12814] [ERROR] connection to ('::', 8794) failed: [Errno 98] Address already in use
scheduler  | [2025-04-16 06:27:57 +0000] [12819] [ERROR] Connection in use: ('::', 8793)
scheduler  | [2025-04-16 06:27:57 +0000] [12819] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
triggerer  | [2025-04-16 06:27:57 +0000] [12814] [ERROR] Can't connect to ('::', 8794)
scheduler  | [2025-04-16 06:27:58 +0000] [12819] [ERROR] Can't connect to ('::', 8793)
scheduler  | Dag run  in running state
scheduler  | Dag information Queued at: 2025-04-16 06:28:44.118167+00:00 hash info: c5a96fe3d75dc1f22d8b3849e42d25a8
scheduler  | [2025-04-16T06:28:46.161+0000] {scheduler_job_runner.py:435} INFO - 1 tasks up for execution:
scheduler  | <TaskInstance: bq_insert_data.insert_sample_rows manual__2025-04-16T06:28:44.093679+00:00 [scheduled]>
scheduler  | [2025-04-16T06:28:46.161+0000] {scheduler_job_runner.py:507} INFO - DAG bq_insert_data has 0/16 running and queued tasks
scheduler  | [2025-04-16T06:28:46.162+0000] {scheduler_job_runner.py:646} INFO - Setting the following tasks to queued state:
scheduler  | <TaskInstance: bq_insert_data.insert_sample_rows manual__2025-04-16T06:28:44.093679+00:00 [scheduled]>
scheduler  | [2025-04-16T06:28:46.163+0000] {scheduler_job_runner.py:748} INFO - Trying to enqueue tasks: [<TaskInstance: bq_insert_data.insert_sample_rows manual__2025-04-16T06:28:44.093679+00:00 [scheduled]>] for executor: SequentialExecutor(parallelism=32)
scheduler  | [2025-04-16T06:28:46.164+0000] {scheduler_job_runner.py:692} INFO - Sending TaskInstanceKey(dag_id='bq_insert_data', task_id='insert_sample_rows', run_id='manual__2025-04-16T06:28:44.093679+00:00', try_number=1, map_index=-1) to SequentialExecutor with priority 1 and queue default
scheduler  | [2025-04-16T06:28:46.164+0000] {base_executor.py:169} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'bq_insert_data', 'insert_sample_rows', 'manual__2025-04-16T06:28:44.093679+00:00', '--local', '--subdir', 'DAGS_FOLDER/bq.py']
scheduler  | [2025-04-16T06:28:46.168+0000] {sequential_executor.py:84} INFO - Executing command: ['airflow', 'tasks', 'run', 'bq_insert_data', 'insert_sample_rows', 'manual__2025-04-16T06:28:44.093679+00:00', '--local', '--subdir', 'DAGS_FOLDER/bq.py']
scheduler  | [2025-04-16T06:28:47.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/adqdevops2/airflow/dags/bq.py
scheduler  | [2025-04-16T06:28:48.015+0000] {tutorial_taskflow_api_virtualenv.py:29} WARNING - The tutorial_taskflow_api_virtualenv example DAG requires virtualenv, please install it.
scheduler  | [2025-04-16T06:28:48.135+0000] {example_python_operator.py:93} WARNING - The virtalenv_python example task requires virtualenv, please install it.
scheduler  | [2025-04-16T06:28:48.152+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
scheduler  | from kubernetes.client import models as k8s
scheduler  | ModuleNotFoundError: No module named 'kubernetes'
scheduler  | [2025-04-16T06:28:48.152+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
scheduler  | [2025-04-16T06:28:48.167+0000] {example_kubernetes_executor.py:39} WARNING - The example_kubernetes_executor example DAG requires the kubernetes provider. Please install it with: pip install apache-airflow[cncf.kubernetes]
scheduler  | [2025-04-16T06:28:48.190+0000] {example_python_decorator.py:80} WARNING - The virtalenv_python example task requires virtualenv, please install it.
scheduler  | [2025-04-16T06:28:48.266+0000] {task_command.py:467} INFO - Running <TaskInstance: bq_insert_data.insert_sample_rows manual__2025-04-16T06:28:44.093679+00:00 [queued]> on host sample.us-east1-b.c.adq-get-project.internal
scheduler  | [2025-04-16T06:28:51.088+0000] {scheduler_job_runner.py:776} INFO - Received executor event with state success for task instance TaskInstanceKey(dag_id='bq_insert_data', task_id='insert_sample_rows', run_id='manual__2025-04-16T06:28:44.093679+00:00', try_number=1, map_index=-1)
scheduler  | [2025-04-16T06:28:51.096+0000] {scheduler_job_runner.py:813} INFO - TaskInstance Finished: dag_id=bq_insert_data, task_id=insert_sample_rows, run_id=manual__2025-04-16T06:28:44.093679+00:00, map_index=-1, run_start_date=2025-04-16 06:28:48.300488+00:00, run_end_date=2025-04-16 06:28:50.622438+00:00, run_duration=2.32195, state=success, executor=SequentialExecutor(parallelism=32), executor_state=success, try_number=1, max_tries=0, job_id=5, pool=default_pool, queue=default, priority_weight=1, operator=BigQueryInsertJobOperator, queued_dttm=2025-04-16 06:28:46.162670+00:00, queued_by_job_id=3, pid=12882
scheduler  | [2025-04-16T06:28:51.238+0000] {dagrun.py:854} INFO - Marking run <DagRun bq_insert_data @ 2025-04-16 06:28:44.093679+00:00: manual__2025-04-16T06:28:44.093679+00:00, state:running, queued_at: 2025-04-16 06:28:44.118167+00:00. externally triggered: True> successful
scheduler  | Dag run in success state
scheduler  | Dag run start:2025-04-16 06:28:46.133195+00:00 end:2025-04-16 06:28:51.239240+00:00
scheduler  | [2025-04-16T06:28:51.239+0000] {dagrun.py:905} INFO - DagRun Finished: dag_id=bq_insert_data, execution_date=2025-04-16 06:28:44.093679+00:00, run_id=manual__2025-04-16T06:28:44.093679+00:00, run_start_date=2025-04-16 06:28:46.133195+00:00, run_end_date=2025-04-16 06:28:51.239240+00:00, run_duration=5.106045, state=success, external_trigger=True, run_type=manual, data_interval_start=2025-04-16 06:28:44.093679+00:00, data_interval_end=2025-04-16 06:28:44.093679+00:00, dag_hash=c5a96fe3d75dc1f22d8b3849e42d25a8
triggerer  | [2025-04-16T06:28:53.273+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
webserver  | ____________       _____________
webserver  | ____    |__( )_________  __/__  /________      __
webserver  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
webserver  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
webserver  | _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
webserver  | Running the Gunicorn Server with:
webserver  | Workers: 4 sync
webserver  | Host: 0.0.0.0:8080
webserver  | Timeout: 120
webserver  | Logfiles: - -
webserver  | Access Logformat:
webserver  | =================================================================
webserver  | [2025-04-16T06:29:51.966+0000] {webserver_command.py:223} ERROR - No response from gunicorn master within 120 seconds
webserver  | [2025-04-16T06:29:51.967+0000] {webserver_command.py:224} ERROR - Shutting down webserver
triggerer  | [2025-04-16T06:29:53.317+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:30:53.375+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:31:53.426+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:32:53.259+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:32:53.482+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:33:53.531+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:34:53.578+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:35:53.623+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:36:53.672+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:37:53.396+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:37:53.717+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:38:53.762+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:39:53.808+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:40:53.857+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:41:53.912+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:42:53.420+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:42:53.966+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:43:54.012+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:44:54.059+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:45:54.107+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:46:54.153+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:47:53.491+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:47:54.194+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:48:54.236+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:49:54.278+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:50:54.334+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:51:54.381+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:52:53.627+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:52:54.431+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:53:54.480+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:54:54.519+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:55:54.564+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:56:54.609+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T06:57:53.647+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T06:57:54.661+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:58:54.704+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T06:59:54.743+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:00:54.796+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:01:54.844+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:02:53.783+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:02:54.896+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:03:54.936+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:04:54.978+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:05:55.023+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:06:55.066+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:07:53.884+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:07:55.106+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:08:55.152+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:09:55.199+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:10:55.255+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:11:55.304+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:12:54.020+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:12:55.351+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:13:55.400+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:14:55.453+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:15:55.492+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:16:55.536+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:17:54.156+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:17:55.579+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:18:55.618+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:19:55.660+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:20:55.713+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:21:55.763+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:22:54.293+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:22:55.809+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:23:55.857+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:24:55.900+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:25:55.949+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:26:55.994+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:27:54.429+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:27:56.033+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:28:56.071+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:29:56.112+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:30:56.163+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:31:56.213+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:32:54.565+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:32:56.263+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:33:56.307+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:34:56.346+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:35:56.381+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:36:56.420+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:37:54.579+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:37:56.468+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:38:56.506+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:39:56.546+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:40:56.598+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:41:56.649+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:42:54.674+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:42:56.699+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:43:56.739+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:44:56.783+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:45:56.820+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:46:56.860+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:47:54.810+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:47:56.894+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:48:56.932+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:49:56.973+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:50:57.025+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:51:57.069+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:52:54.946+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:52:57.114+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:53:57.158+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:54:57.202+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:55:57.244+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:56:57.281+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T07:57:55.082+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T07:57:57.329+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:58:57.373+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T07:59:57.428+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:00:57.480+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:01:57.522+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:02:55.318+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:02:57.566+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:03:57.606+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:04:57.649+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:05:57.689+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:06:57.732+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:07:55.440+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:07:57.775+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:08:57.826+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:09:57.874+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:10:57.932+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:11:57.972+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:12:55.575+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:12:58.024+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:13:58.067+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:14:58.111+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:15:58.162+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:16:58.204+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:17:55.709+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:17:58.246+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:18:58.290+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:19:58.332+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:20:58.381+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:21:58.433+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:22:55.842+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:22:58.478+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:23:58.522+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:24:58.568+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:25:58.608+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:26:58.653+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:27:55.980+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:27:58.692+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:28:58.733+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:29:58.773+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:30:58.831+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:31:58.880+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:32:56.117+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:32:58.921+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:33:58.965+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:34:59.013+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:35:59.067+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:36:59.109+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:37:56.253+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:37:59.148+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:38:59.193+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:39:59.243+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:40:59.296+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:41:59.340+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:42:56.389+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:42:59.383+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:43:59.427+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:44:59.465+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:45:59.503+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:46:59.543+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:47:56.526+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:47:59.587+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:48:59.636+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:49:59.680+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:50:59.734+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:51:59.784+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:52:56.585+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:52:59.830+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:53:59.877+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:54:59.924+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:55:59.970+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:57:00.017+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T08:57:56.725+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T08:58:00.060+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T08:59:00.102+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:00:00.150+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:01:00.206+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:02:00.251+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:02:56.777+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:03:00.294+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:04:00.332+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:05:00.374+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:06:00.418+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:07:00.462+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:07:56.914+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:08:00.506+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:09:00.553+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:10:00.598+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:11:00.652+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:12:00.703+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:12:57.050+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:13:00.753+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:14:00.796+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:15:00.842+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:16:00.893+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:17:00.935+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:17:57.185+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:18:00.978+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:19:01.017+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:20:01.058+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:21:01.111+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:22:01.160+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:22:57.322+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:23:01.205+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:24:01.249+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:25:01.293+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:26:01.339+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:27:01.384+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:27:57.459+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:28:01.434+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:29:01.482+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:30:01.529+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:31:01.580+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:32:01.626+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | [2025-04-16T09:32:57.596+0000] {scheduler_job_runner.py:1949} INFO - Adopting or resetting orphaned tasks for active dag runs
triggerer  | [2025-04-16T09:33:01.672+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:34:01.717+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:35:01.765+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:36:01.808+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
triggerer  | [2025-04-16T09:37:01.847+0000] {triggerer_job_runner.py:510} INFO - 0 triggers currently running
scheduler  | Process ForkProcess-2:
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlite3.OperationalError: unable to open database file
scheduler  | The above exception was the direct cause of the following exception:
scheduler  | Traceback (most recent call last):
scheduler  | File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
scheduler  | self.run()
scheduler  | File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
scheduler  | self._target(*self._args, **self._kwargs)
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 247, in _run_processor_manager
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 489, in start
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 626, in _run_parsing_loop
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/dagwarning.py", line 82, in purge_inactive_dag_warnings
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 443, in __iter__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 376, in iter
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 418, in exc_check
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 185, in reraise
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
scheduler  | return self.__get_result()
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
scheduler  | raise self._exception
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/dagwarning.py", line 95, in _purge_inactive_dag_warnings_with_retry
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
scheduler  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
scheduler  | [2025-04-16T09:37:38.335+0000] {scheduler_job_runner.py:1016} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlite3.OperationalError: unable to open database file
scheduler  | The above exception was the direct cause of the following exception:
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 999, in _execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1138, in _run_scheduler_loop
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1244, in _do_scheduling
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 443, in __iter__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 376, in iter
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 418, in exc_check
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 185, in reraise
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
scheduler  | return self.__get_result()
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
scheduler  | raise self._exception
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1312, in _create_dagruns_for_dags
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/dag.py", line 4086, in dags_needing_dagruns
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
scheduler  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
scheduler  | [2025-04-16T09:37:38.339+0000] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 12820. PIDs of all processes in the group: []
scheduler  | [2025-04-16T09:37:38.340+0000] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 12820
scheduler  | [2025-04-16T09:37:38.340+0000] {process_utils.py:101} INFO - Sending the signal Signals.SIGTERM to process 12820 as process group is missing.
scheduler  | [2025-04-16T09:37:38.340+0000] {scheduler_job_runner.py:1029} INFO - Exited execute loop
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlite3.OperationalError: unable to open database file
scheduler  | The above exception was the direct cause of the following exception:
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 421, in run_job
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 450, in execute_job
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 999, in _execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1138, in _run_scheduler_loop
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1244, in _do_scheduling
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 443, in __iter__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 376, in iter
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 418, in exc_check
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 185, in reraise
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
scheduler  | return self.__get_result()
scheduler  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
scheduler  | raise self._exception
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 1312, in _create_dagruns_for_dags
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/dag.py", line 4086, in dags_needing_dagruns
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
scheduler  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
scheduler  | During handling of the above exception, another exception occurred:
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlite3.OperationalError: unable to open database file
scheduler  | The above exception was the direct cause of the following exception:
scheduler  | Traceback (most recent call last):
scheduler  | File "/home/adqdevops2/airflow-env/bin/airflow", line 8, in <module>
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/__main__.py", line 62, in main
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 56, in scheduler
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 59, in <lambda>
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 423, in run_job
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 94, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 273, in complete_execution
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 94, in wrapper
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 359, in _update_in_db
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
scheduler  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
scheduler  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
scheduler  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
triggerer  | [2025-04-16T09:37:38.407+0000] {triggerer_job_runner.py:348} ERROR - Exception when executing TriggererJobRunner._run_trigger_loop
triggerer  | Traceback (most recent call last):
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
triggerer  | sqlite3.OperationalError: unable to open database file
triggerer  | The above exception was the direct cause of the following exception:
triggerer  | Traceback (most recent call last):
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/triggerer_job_runner.py", line 346, in _execute
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/triggerer_job_runner.py", line 370, in _run_trigger_loop
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/trigger.py", line 174, in clean_unused
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 443, in __iter__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 376, in iter
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 418, in exc_check
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 185, in reraise
triggerer  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
triggerer  | return self.__get_result()
triggerer  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
triggerer  | raise self._exception
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/trigger.py", line 176, in clean_unused
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
triggerer  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
triggerer  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
triggerer  | [2025-04-16T09:37:38.407+0000] {triggerer_job_runner.py:351} INFO - Waiting for triggers to clean up
triggerer  | [2025-04-16T09:37:38.874+0000] {triggerer_job_runner.py:357} INFO - Exited trigger loop
triggerer  | Traceback (most recent call last):
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
triggerer  | sqlite3.OperationalError: unable to open database file
triggerer  | The above exception was the direct cause of the following exception:
triggerer  | Traceback (most recent call last):
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 421, in run_job
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/job.py", line 450, in execute_job
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/triggerer_job_runner.py", line 346, in _execute
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/jobs/triggerer_job_runner.py", line 370, in _run_trigger_loop
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/trigger.py", line 174, in clean_unused
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 443, in __iter__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 376, in iter
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 418, in exc_check
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/tenacity/__init__.py", line 185, in reraise
triggerer  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
triggerer  | return self.__get_result()
triggerer  | File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
triggerer  | raise self._exception
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/airflow/models/trigger.py", line 176, in clean_unused
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
triggerer  | File "/home/adqdevops2/airflow-env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
triggerer  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
triggerer  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
triggerer  | During handling of the above exception, another exception occurred:
triggerer  | Traceback (most recent call last):
